{
	"version": 1730938919,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/juego de nave 2,1/fondo.png",
		"images/juego de nave 2,1/nave-sheet0.png",
		"images/juego de nave 2,1/laser-sheet0.png",
		"images/juego de nave 2,1/sprite-sheet0.png",
		"images/juego de nave 2,1/sprite-sheet1.png",
		"images/juego de nave 2,1/sprite2-sheet0.png",
		"images/juego de nave 2,1/enemigo1-sheet0.png",
		"images/juego de nave 2,1/enemigo2-sheet0.png",
		"images/juego de nave 2,1/enemigo5-sheet0.png",
		"images/juego de nave 2,1/limiteizquierdo-sheet0.png",
		"images/juego de nave 2,1/tiledbackground.png",
		"images/juego de nave 2,1/sprite4-sheet0.png",
		"images/juego de nave 2,1/enemybullet-sheet0.png",
		"images/juego de nave 2,1/tiledbackground2.png",
		"images/juego de nave 2,1/tiledbackground3.png",
		"media/escritorio/song.ogg",
		"media/escritorio/pistola-laser.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}